/**
 * Offline Sync Queue Manager.
 * Internet download/upload disconnect avvataniki ready, local storage register chesi track chestundi.
 */
class SyncQueueManager {
  constructor() {
    this.storageKey = 'ecomeal_offline_queue';
    this.isSyncing = false;
    this.syncCallbacks = [];
  }

  // Retrieve current queued operations from local storage
  getQueue() {
    try {
      const data = localStorage.getItem(this.storageKey);
      return data ? JSON.parse(data) : [];
    } catch (err) {
      console.error('Failed to parse offline sync queue:', err);
      return [];
    }
  }

  // Save the modified queue back to local storage
  saveQueue(queue) {
    try {
      localStorage.setItem(this.storageKey, JSON.stringify(queue));
    } catch (err) {
      console.error('Failed to save offline sync queue:', err);
    }
  }

  /**
   * Enqueue a new mutation operation
   * @param {string} action - 'create' | 'update' | 'delete'
   * @param {string} itemId - The ID of the item (if update/delete)
   * @param {object} data - The inventory item payload
   */
  enqueue(action, itemId, data) {
    let queue = this.getQueue();
    const timestamp = new Date().getTime();

    // De-duplication logic:
    // If we update an item multiple times offline, just merge the updates
    if (action === 'update') {
      const existingUpdateIdx = queue.findIndex(
        (item) => item.action === 'update' && item.itemId === itemId
      );
      if (existingUpdateIdx > -1) {
        // Merge payloads
        queue[existingUpdateIdx].data = {
          ...queue[existingUpdateIdx].data,
          ...data,
        };
        queue[existingUpdateIdx].timestamp = timestamp;
        this.saveQueue(queue);
        return;
      }

      // If we update a newly created item offline, merge into the create request
      const existingCreateIdx = queue.findIndex(
        (item) => item.action === 'create' && item.data.tempId === itemId
      );
      if (existingCreateIdx > -1) {
        queue[existingCreateIdx].data = {
          ...queue[existingCreateIdx].data,
          ...data,
        };
        queue[existingCreateIdx].timestamp = timestamp;
        this.saveQueue(queue);
        return;
      }
    }

    // If we delete an item that was created offline and not synced yet, remove it from queue entirely
    if (action === 'delete') {
      const existingCreateIdx = queue.findIndex(
        (item) => item.action === 'create' && item.data.tempId === itemId
      );
      if (existingCreateIdx > -1) {
        queue = queue.filter((item) => !(item.action === 'create' && item.data.tempId === itemId));
        this.saveQueue(queue);
        return;
      }

      // Remove any updates to this item, keeping only the final delete
      queue = queue.filter(
        (item) => !(item.itemId === itemId && (item.action === 'update' || item.action === 'delete'))
      );
    }

    // Append new operation
    queue.push({
      action,
      itemId,
      data,
      timestamp,
    });

    this.saveQueue(queue);
    console.log(`Queued offline action [${action}] for item:`, itemId || data.name);
  }

  /**
   * Register callbacks to notify UI when sync succeeds
   */
  onSyncCompleted(callback) {
    this.syncCallbacks.push(callback);
  }

  /**
   * Process all queued items sequentially.
   * Server link confirm response check, retry on network crash.
   */
  async processQueue(authenticatedFetch, apiUrl) {
    if (this.isSyncing) return;
    
    const queue = this.getQueue();
    if (queue.length === 0) return;

    console.log(`Starting synchronization of ${queue.length} offline operations...`);
    this.isSyncing = true;

    // Track temp ID mappings to real database IDs generated by MongoDB
    const idMap = {};

    let successCount = 0;
    const remainingQueue = [];

    for (const op of queue) {
      try {
        let url = `${apiUrl}/inventory`;
        let method = 'POST';
        let body = { ...op.data };

        // Handle offline creates with tempIds
        if (op.action === 'create') {
          // Send request to server
          const response = await authenticatedFetch(url, {
            method,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
          });

          if (!response.ok) throw new Error(`Server returned status ${response.status}`);
          const resData = await response.json();

          // Store mapping if we created a temp item
          if (op.data.tempId && resData.success) {
            idMap[op.data.tempId] = resData.data._id;
          }
          successCount++;
        } else if (op.action === 'update') {
          method = 'PUT';
          // Resolve ID mapping if it was created offline in the same session
          const targetId = idMap[op.itemId] || op.itemId;
          url = `${apiUrl}/inventory/${targetId}`;

          const response = await authenticatedFetch(url, {
            method,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body),
          });

          if (!response.ok) throw new Error(`Server returned status ${response.status}`);
          successCount++;
        } else if (op.action === 'delete') {
          method = 'DELETE';
          const targetId = idMap[op.itemId] || op.itemId;
          url = `${apiUrl}/inventory/${targetId}`;

          const response = await authenticatedFetch(url, { method });

          if (!response.ok) throw new Error(`Server returned status ${response.status}`);
          successCount++;
        }
      } catch (err) {
        console.error(`Offline sync failed for operation [${op.action}] on ID [${op.itemId}]:`, err.message);
        // Keep in queue for next retry if it's a network error (not validation)
        remainingQueue.push(op);
      }
    }

    this.saveQueue(remainingQueue);
    this.isSyncing = false;

    console.log(`Sync complete. Successfully processed: ${successCount}. Remaining in queue: ${remainingQueue.length}`);

    // Trigger registered callbacks to notify the UI to refresh
    if (successCount > 0) {
      this.syncCallbacks.forEach((cb) => cb());
    }
  }
}

export const syncQueue = new SyncQueueManager();
